/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

type AddressList struct {
	// The addresses returned in this set.
	Data []AddressLink `json:"data"`
	// The index of the first address returned from the total set (Starting from 0).
	Offset int32 `json:"offset"`
	// The number of addresses returned per page.
	Limit int32 `json:"limit"`
	// The total number of addresses seen.
	Count int32 `json:"count"`
}
