/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// Represents a list of Factom entries that have been or will be saved to the blockchain.
type Chain struct {
	Data ChainData `json:"data"`
}
