/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.17
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

type ChainData struct {
	// This is the unique identifier created for each chain.
	ChainId string `json:"chain_id"`
	// Tags that have been used to identify this entry.
	ExternalIds []string `json:"external_ids"`
	// The immutability stage that this chain has reached.
	Stage string `json:"stage"`
	Entries ChainDataEntries `json:"entries"`
}
