/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// Contains information about the desired Directory Block Anchor.
type AnchorLongData struct {
	Dblock DBlockLink `json:"dblock"`
	// A list of all the anchors of this Directory Block.
	Anchors []SingleAnchor `json:"anchors"`
}
