/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// A single factoid transaction.
type TransactionShort struct {
	// The transaction ID for this transaction.
	TxId string `json:"tx_id,omitempty"`
	// The timestamp for this transaction. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: `YYYY-MM-DDThh:mm:ssZ`
	CreatedAt string `json:"created_at,omitempty"`
	// A link to the directory block that contains this transaction.
	Dblock string `json:"dblock,omitempty"`
	// A link to the factoid block that contains this transaction.
	Fblock string `json:"fblock,omitempty"`
	// An API link to obtain all data for this transaction.
	Href string `json:"href,omitempty"`
	// All of the input transactions for this transaction.
	Inputs string `json:"inputs,omitempty"`
	// All of the output transactions for this transaction.
	Outputs string `json:"outputs,omitempty"`
	// The number of entry credits that have been purchased in this transaction.
	OutEcs string `json:"out_ecs,omitempty"`
}
