/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// The next entry block within the parent directory block.
type EBlockLongNext struct {
	// The Key Merkle Root for this entry block.
	Keymr string `json:"keymr,omitempty"`
	// An API link to retrieve all information about this entry block.
	Href string `json:"href,omitempty"`
}
