/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

type SingleAnchor struct {
	// Indicates the blockchain network that contains this anchor.
	Network string `json:"network"`
	// The confirmation status of the anchor. Either pending or confirmed.
	Status string `json:"status"`
	// Only returned for confirmed bitcoin or ethereum anchors. The bitcoin or ethereum transaction ID for the transaction that includes the anchor message.
	TxId string `json:"tx_id,omitempty"`
	// Only returned for confirmed bitcoin or ethereum anchors. The hash of the bitcoin or ethereum block that contains the anchor message.
	BlockHash string `json:"block_hash,omitempty"`
	// Only returned for confirmed factom anchors. The time at which this entry was created. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: `YYYY-MM-DDThh:mm:ss.ssssssZ` This will be null if the chain is not at least at the `factom` immutability stage.
	CreatedAt string `json:"created_at,omitempty"`
	// Only returned for confirmed factom anchors. The raw data that makes up the entry.
	EntrySerialized string `json:"entry_serialized,omitempty"`
	// Only returned for confirmed factom anchors. The unique identitfier of the entry.
	EntryHash string `json:"entry_hash,omitempty"`
	Dblock DBlockLink `json:"dblock,omitempty"`
	// Only returned for confirmed factom or ethereum anchors. The branch of the merkle tree that represents this anchor. Presented as an array of Merkle nodes.
	MerkleBranch []MerkleNode `json:"merkle_branch,omitempty"`
	// Only returned for confirmed ethereum anchors. The height of the first ethereum block that contains an anchor for this directory block. Valid anchors for the Directory block in question may also be contained in subsequent ethereum blocks.
	WindowStartHeight int32 `json:"window_start_height,omitempty"`
	// Only returned for confirmed ethereum anchors. Window Merkle Root. This is the Merkle root that was published in the ethereum transaction that anchors this directory block. The root represents every one of the 1000 Directory blocks that's included in this anchor.
	WindowMr string `json:"window_mr,omitempty"`
	// Only returned for confirmed ethereum anchors. The address of the contract that initiated the anchor transaction.
	ContractAddress string `json:"contract_address,omitempty"`
	// Only returned for confirmed ethereum anchors. The index of the transaction within the block.
	TxIndex int32 `json:"tx_index,omitempty"`
}
