/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

type CommitLong struct {
	// The SHA256 Hash of this commit.
	Hash string `json:"hash"`
	// The entry credit transaction ID that resulted in this commit.
	TxId string `json:"tx_id"`
	// The type version of this transaction.
	Version int32 `json:"version"`
	// The timestamp for when this commit was created. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: `YYYY-MM-DDThh:mm:ssZ`
	CreatedAt string `json:"created_at"`
	// The ID of the chain that was altered by this commit.
	ChainId string `json:"chain_id"`
	// The commit weld for this commit. This is the double hash (SHA256d) of the Entry Hash concatenated with the ChainID.
	Weld string `json:"weld"`
	// The unique identifier of the entry that was created by this commit.
	EntryHash string `json:"entry_hash"`
	// The number of entry credits spent on this commit.
	EntryCredits int32 `json:"entry_credits"`
	// The entry credit address that initiated this transaction.
	Address string `json:"address"`
	// The signature that authorized this commit.
	Signature string `json:"signature"`
	EcBlock EcBlockShort `json:"ec_block,omitempty"`
}
