/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.17
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// A paginated list of entries.
type EntryList struct {
	// An array that contains the entries on this page.
	Data []EntryListData `json:"data"`
	// The first entry returned from the total set (Starting from 0).
	Offset int32 `json:"offset"`
	// The number of entries returned.
	Limit int32 `json:"limit"`
	// The total number of entries seen.
	Count int32 `json:"count"`
}
