/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// A single Directory block from the factom blockchain.
type DBlockShort struct {
	// The height of a directory block indicates how many blocks were created before this block. This is used to identify blocks in the blockchain.
	Height int32 `json:"height,omitempty"`
	// The timestamp for when this block was built. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: `YYYY-MM-DDThh:mm:ssZ`
	StartedAt string `json:"started_at,omitempty"`
	// The Key Merkle Root for this block.
	Keymr string `json:"keymr,omitempty"`
	// The link to retrieve all information for this directory block.
	Href string `json:"href,omitempty"`
	// The number of entries contained in the admin block.
	AdminEntries string `json:"admin_entries,omitempty"`
	// The number of entries contained in the entry credit block.
	EcEntries string `json:"ec_entries,omitempty"`
	// The number of entries contained in the factoid block.
	FactoidEntries string `json:"factoid_entries,omitempty"`
	// The number of entries contained in the entry blocks.
	Entries string `json:"entries,omitempty"`
}
