/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

type IdentityChain struct {
	// The Identity Chain’s schema version. This details the format of this digital identity. More information about Factom Identity Chain schemas can be seen [here]().
	Version string `json:"version"`
	// The immutability stage that this chain has reached. The identity can be considered in use once it reaches the `factom` stage.
	Stage string `json:"stage"`
	// The block height at which this chain was written into the Factom blockchain. This is `null` if the chain has not reached the `factom` stage.
	CreatedHeight int32 `json:"created_height,omitempty"`
	// The Chain ID for this identity chain.
	ChainId string `json:"chain_id"`
	// A unique array of strings that are associated with this identity.
	Name []string `json:"name"`
	// Contains the currently active public keys for this identity.
	ActiveKeys []IdentityKeyShort `json:"active_keys"`
	// An API link to retrieve the keys for this identity.
	AllKeysHref string `json:"all_keys_href"`
}
