/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

type AllInfo struct {
	// Current version of the Connect API
	Version string `json:"version"`
	Links AllInfoLinks `json:"links"`
}
