/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

type EthereumAnchor struct {
	// Indicates the blockchain network that contains this anchor.
	Network string `json:"network"`
	// The confirmation status of the anchor. Either pending or confirmed.
	Status string `json:"status"`
	// The height of the first ethereum block that contains an anchor for this directory block. Valid anchors for the Directory block in question may also be contained in subsequent ethereum blocks.
	WindowStartHeight int32 `json:"window_start_height,omitempty"`
	// Window Merkle Root. This is the Merkle root that was published in the ethereum transaction that anchors this directory block. The root represents every one of the 1000 Directory blocks that's included in this anchor.
	WindowMr string `json:"window_mr,omitempty"`
	// The merkle branch that leads to the Directory block in question. Relates to the Window Merkle root. Presented as an array of Merkle nodes.
	MerkleBranch []MerkleNode `json:"merkle_branch,omitempty"`
	// The address of the contract that initiated the anchor transaction.
	ContractAddress string `json:"contract_address,omitempty"`
	// The ethereum transaction ID for the transaction that includes the anchor message.
	TxId string `json:"tx_id,omitempty"`
	// The index of the transaction within the block.
	TxIndex int32 `json:"tx_index,omitempty"`
	// The hash of the ethereum block that contains the anchor transaction.
	BlockHash string `json:"block_hash,omitempty"`
}
