/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.17
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

type ChainData struct {
	// This is the unique identifier created for each chain.
	ChainId string `json:"chain_id"`
	// This is the data that was stored in the first entry of this chain.
	Content string `json:"content"`
	// Tags that have been used to identify this entry.
	ExternalIds []string `json:"external_ids"`
	// The immutability stage that this chain has reached.
	Stage string `json:"stage"`
	Entries ChainDataEntries `json:"entries"`
	Eblock ChainDataEblock `json:"eblock"`
	Dblock ChainDataDblock `json:"dblock"`
	// The time at which this chain was created. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: `YYYY-MM-DDThh:mm:ss.ssssssZ` This will be null if the chain is not at least at the `factom` immutability stage.
	CreatedAt string `json:"created_at"`
}
