/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// The next admin block.
type ABlockLongNext struct {
	// The SHA256 hash of this admin block.
	Hash string `json:"hash,omitempty"`
	// An API link to this Admin block.
	Href string `json:"href,omitempty"`
}
