/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// A factoid or entry credit address.
type Address struct {
	// The literal address.
	Address string `json:"address,omitempty"`
	// The user address.
	UserAddress string `json:"user_address,omitempty"`
	// Whether this is an entry credit or factoid address.
	Type string `json:"type,omitempty"`
	// The current entry credit or factoid balance of the address.
	Balance string `json:"balance,omitempty"`
	// A list of all transactions that this address has paricipated in.
	Transactions map[string]interface{} `json:"transactions,omitempty"`
}
