/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// The directory block that contains this factoid block.
type ABlockLongDblock struct {
	// The Key Merkle root of the directory block.
	Keymr string `json:"keymr,omitempty"`
	// An API link to the directory block.
	Href string `json:"href,omitempty"`
}
