/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// A link to a factoid or entry credit address.
type AddressLink struct {
	// The literal address.
	Address string `json:"address,omitempty"`
	// The user address.
	UserAddress string `json:"user_address,omitempty"`
	// An API link to obtain all data about this address.
	Href string `json:"href,omitempty"`
}
