/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// The previous directory block in the Factom blockchain.
type DBlockLongPrev struct {
	// The Key Merkle Root for this directory block.
	Keymr string `json:"keymr,omitempty"`
	// The Factom block height.
	Height string `json:"height,omitempty"`
	// An API link to retrieve all information about this directory block.
	Href string `json:"href,omitempty"`
}
