/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

type IdentityKeyReplace struct {
	// The public key you would like to replace. This should be sent as a Base58 string in IdPub format.
	OldKey string `json:"old_key"`
	// The public key that you would like to activate. This should be sent as a Base58 string in IdPub format.
	NewKey string `json:"new_key"`
	// The key you are using to authorize the replacement. Must be equal to or higher level than the key you want to replace. This should be sent as a Base58 string in IdPub format.
	SignerKey string `json:"signer_key"`
	// A signature that proves ownership of the `signer_key`. This signature should use the [Ed25519](https://ed25519.cr.yp.to/) specification. The signed message should be the Identity Chain ID, the Old Key, and the New Key in that order. The message should be a single string with no whitespace or separators between the three parts.
	Signature string `json:"signature"`
	// The URL where you would like to receive the callback from Connect. If this is not specified, callbacks will not activate.
	CallbackUrl string `json:"callback_url,omitempty"`
	// The stages that you would like to trigger a callback from Connect. This list can include any or all of the three stages: `replicated`, `factom`, and `anchored`. If callbacks are activated and this field is not sent, it will default to `factom` and `anchored`
	CallbackStages []string `json:"callback_stages,omitempty"`
}
