/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// Represents the Directory Block that relates to this chain. This will be null if the chain is not at least at the `factom` immutability stage.
type ChainDataDblock struct {
	// The Key Merkle Root for this directory block.
	Keymr string `json:"keymr,omitempty"`
	// The Factom blockchain height of this directory block.
	Height int32 `json:"height,omitempty"`
	// An API link to retrieve all information about this directory block.
	Href string `json:"href,omitempty"`
}
