/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// A single factoid block from the factom blockchain.
type FBlockShort struct {
	// The SHA256 Hash of this entry.
	Keymr string `json:"keymr,omitempty"`
	// An API link to obtain the full set of data for this factoid block.
	Href string `json:"href,omitempty"`
	Dblock ABlockLongDblock `json:"dblock,omitempty"`
	// The Entry credit rate at the time this block was created.
	EcRate string `json:"ec_rate,omitempty"`
	// The number of factoid transactions that occur in this block.
	Transactions string `json:"transactions,omitempty"`
}
