/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// A single Directory block from the factom blockchain.
type DBlockLong struct {
	// The height of a directory block indicates how many blocks were created before this block. This is used to identify blocks in the blockchain.
	Height string `json:"height,omitempty"`
	// The timestamp for when this block was built. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: `YYYY-MM-DDThh:mm:ssZ`
	StartedAt string `json:"started_at,omitempty"`
	// The Key Merkle Root for this block.
	Keymr []string `json:"keymr,omitempty"`
	BtcAnchorEntry DBlockLongBtcAnchorEntry `json:"btc_anchor_entry,omitempty"`
	// The bitcoin block hash for the bitcoin anchor that matches this directory block.
	BtcBlockHash string `json:"btc_block_hash,omitempty"`
	// The bitcoin transaction ID for the transaction that includes the anchor message.
	BtcTransaction string `json:"btc_transaction,omitempty"`
	Prev DBlockLongPrev `json:"prev,omitempty"`
	Next DBlockLongNext `json:"next,omitempty"`
	Ablock DBlockLongAblock `json:"ablock,omitempty"`
	Ecblock DBlockLongEcblock `json:"ecblock,omitempty"`
	Fblock DBlockLongFblock `json:"fblock,omitempty"`
	// The entry blocks contained in this directory block.
	Eblocks []DBlockLongEblocks `json:"eblocks,omitempty"`
}
