/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

type EBlockShort struct {
	// The Key Merkle Root for this entry block.
	Keymr string `json:"keymr"`
	Chain EBlockShortChain `json:"chain"`
	Dblock EBlockShortDblock `json:"dblock"`
	// The timestamp for when this block was built. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: `YYYY-MM-DDThh:mm:ssZ`
	StartedAt map[string]interface{} `json:"started_at"`
	// An API link to retrieve all information about this entry block.
	Href string `json:"href"`
	// The number of entries contained within this entry block.
	Entries int32 `json:"entries"`
}
