/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// A single Admin block from the factom blockchain.
type ABlockLong struct {
	// The SHA256 Hash of this block.
	Hash string `json:"hash,omitempty"`
	// The hash of the previous admin block.
	BackReferenceHash string `json:"back_reference_hash,omitempty"`
	Prev ABlockLongPrev `json:"prev,omitempty"`
	Next ABlockLongNext `json:"next,omitempty"`
	Dblock ABlockLongDblock `json:"dblock,omitempty"`
	// The entries contained in this admin block.
	Entries string `json:"entries,omitempty"`
}
