/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

type IdentityKeyShortData struct {
	// The public key.
	Key string `json:"key"`
	// The height at which this key became valid. `null` if this is the first key.
	ActivatedHeight int32 `json:"activated_height,omitempty"`
	// The expiration height of this key. `null` if this is the current key.
	RetiredHeight int32 `json:"retired_height,omitempty"`
}
