/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// An object that contains the Entry Hash (ID) and a URL for the entry.
type DBlockLongBtcAnchorEntry struct {
	// The unique identitfier of the entry.
	EntryHash string `json:"entry_hash,omitempty"`
	Chain DBlockLongBtcAnchorEntryChain `json:"chain,omitempty"`
	// The time at which this entry was created. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: `YYYY-MM-DDThh:mm:ssZ`
	CreatedAt string `json:"created_at,omitempty"`
	// An API link to retrieve all information about this entry.
	Href string `json:"href,omitempty"`
}
