/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// This information will be used to create a new entry.
type EntryCreate struct {
	// Tags that can be used to identify your entry. You can search for records that contain a particular `external_id` using Connect. External IDs should be sent in Base64.
	ExternalIds []string `json:"external_ids"`
	// This is the data that will be stored directly on the blockchain. Please be sure that no private information is entered here. Content should be sent in Base64 format.
	Content string `json:"content"`
	// The address you'd like the callback to be sent to. If this is not specified, callbacks will not activate.
	CallbackUrl string `json:"callback_url,omitempty"`
	// The immutability stages you'd like to be notified about. This list can include any or all of the three stages: `replicated`, `factom`, and `anchored`. If callbacks are activated and this field is not sent, it will default to `factom` and `anchored`
	CallbackStages []string `json:"callback_stages,omitempty"`
}
