/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// A single entry credit block from the factom blockchain.
type EcBlockLong struct {
	// The SHA256 Hash of this entry credit block.
	Hash string `json:"hash,omitempty"`
	Dblock EcBlockLongDblock `json:"dblock,omitempty"`
	// The entries contained in this admin block.
	Entries string `json:"entries,omitempty"`
}
