/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.17
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// Used to create a new chain on Connect.
type ChainCreate struct {
	// Tags that can be used to identify your chain. You can search for records that contain a particular external_id using Connect. You must send External IDs in Base64 format.
	ExternalIds []string `json:"external_ids"`
	// This is the data that will make up the first entry in your new chain. It is customary to use this space to describe the entries that are to follow in the chain. You must send the content field in Base64 format.
	Content string `json:"content"`
	// The URL where you would like to receive the callback from Connect. If this is not specified, callbacks will not activate.
	CallbackUrl string `json:"callback_url,omitempty"`
	// The stages that you would like to trigger a callback from Connect. This list can include any or all of the three stages: `replicated`, `factom`, and `anchored`. If callbacks are activated and this field is not sent, it will default to `factom` and `anchored`
	CallbackStages []string `json:"callback_stages,omitempty"`
}
