/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.17
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// Represents a list of Factom entries that have been or will be saved to the blockchain.
type ChainList struct {
	// An array that contains the chains on this page.
	Data []ChainListData `json:"data"`
	// The page offset. (Current page -1)
	Offset string `json:"offset"`
	// The maximum number of chains per page.
	Limit string `json:"limit"`
	// The total number of chains seen.
	Count string `json:"count"`
}
