/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.17
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

type EntryData struct {
	// The SHA256 Hash of this entry.
	EntryHash string `json:"entry_hash,omitempty"`
	Chain EntryLinkChain `json:"chain,omitempty"`
	// The time when this entry was created. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: `YYYY-MM-DDThh:mm:ssZ`
	CreatedAt string `json:"created_at,omitempty"`
	// Tags that can be used to identify your entry. You can search for records that contain a particular external_id using Connect. External IDs are returned in Base64.
	ExternalIds []string `json:"external_ids,omitempty"`
	// This is the data that is stored by the entry. Content will be sent in Base64 format.
	Content string `json:"content,omitempty"`
	// The level of immutability that this entry has reached.
	Stage string `json:"stage,omitempty"`
	Eblock EntryDataEblock `json:"eblock,omitempty"`
}
