/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

type BitcoinAnchor struct {
	// Indicates the blockchain network that contains this anchor.
	Network string `json:"network"`
	// The confirmation status of the anchor. Either pending or confirmed.
	Status string `json:"status"`
	// The bitcoin transaction ID for the transaction that includes the anchor message.
	TxId string `json:"tx_id,omitempty"`
	// The hash of the bitcoin block that contains the anchor message.
	BlockHash string `json:"block_hash,omitempty"`
}
