/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.17
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

type ChainListData struct {
	// The ID for this chain on the Factom blockchain.
	ChainId string `json:"chain_id"`
	// The external IDs attached to this chain on the Factom blockchain.
	ExternalIds []string `json:"external_ids"`
	// An API link to retrieve all information about this chain.
	Href string `json:"href"`
}
