/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// A single Admin block from the factom blockchain.
type ABlockShort struct {
	// The SHA256 Hash of this block.
	Hash string `json:"hash,omitempty"`
	// A link to retrieve all data for this admin block.
	Href string `json:"href,omitempty"`
	Dblock ABlockShortDblock `json:"dblock,omitempty"`
}
