/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// The entry credit block contained in this directory block.
type DBlockLongEcblock struct {
	// The Key Merkle Root for this entry credit block.
	Keymr string `json:"keymr,omitempty"`
	// The Factom block height.
	Height string `json:"height,omitempty"`
	// An API link to retrieve all information about this entry credit block.
	Href string `json:"href,omitempty"`
}
