/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

type ErrorMessage struct {
	// A list of errors caused by the previous request.
	Errors []ErrorMessageErrors `json:"errors"`
}
