/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.17
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// The external IDs of the chains or entries you want to retrieve. You must enter these External IDs in Base64 format.
type SearchBody struct {
	// A list of external IDs.
	ExternalIds []string `json:"external_ids"`
}
