/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

type IdentityCreate struct {
	// A unique array of strings that together constitute the Identity's name. Each string should be in Base64 format.   *Note: It is best to avoid adding personally identifiable information to the blockchain.*
	Names []string `json:"names"`
	// A list of public keys that will be used to verify this Indenty’s signatures. You may initiate an identity with as many keys as you like. The array of keys should be sent in order of priority with 0 being the master key. The keys should be sent as Base58 strings in IdPub format.
	Keys []string `json:"keys"`
	// The URL where you would like to receive the callback from Connect. If this is not specified, callbacks will not activate.
	CallbackUrl string `json:"callback_url,omitempty"`
	// The stages that you would like to trigger a callback from Connect. This list can include any or all of the three stages: `replicated`, `factom`, and `anchored`. If callbacks are activated and this field is not sent, it will default to `factom` and `anchored`
	CallbackStages []string `json:"callback_stages,omitempty"`
}
