/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// A single factoid block from the factom blockchain.
type FBlockLong struct {
	// The SHA256 Hash of this entry.
	Keymr string `json:"keymr,omitempty"`
	Prev FBlockLongPrev `json:"prev,omitempty"`
	Next FBlockLongNext `json:"next,omitempty"`
	Dblock ABlockLongDblock `json:"dblock,omitempty"`
	// The Entry credit rate at the time this block was created.
	EcRate string `json:"ec_rate,omitempty"`
	// The number of factoid inputs in this block.
	FctTotalInputs string `json:"fct_total_inputs,omitempty"`
	// The number of factoid outputs in this block.
	FctTotalOutputs string `json:"fct_total_outputs,omitempty"`
	// The total number of entry credits purchased in this block.
	EcTotalCreated string `json:"ec_total_created,omitempty"`
	// A list of all of the transactions that occur in this block.
	Transactions string `json:"transactions,omitempty"`
}
