/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// A link to the next factoid block in the chain.
type FBlockLongNext struct {
	// The Key Merkle root of the factoid block.
	Keymr string `json:"keymr,omitempty"`
	// An API link to the factoid block.
	Href string `json:"href,omitempty"`
}
