/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// Contains information about a single error.
type ErrorMessageErrors struct {
	// A detailed description of the error.
	Details string `json:"details"`
}
