/*
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * API version: 1.0.17
 * Contact: harmony-support@factom.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connectclient

// A paginated list of entries.
type EntryList struct {
	// An array that contains the entries on this page.
	Data []EntryListData `json:"data"`
	// The page offset. (Current page -1)
	Offset string `json:"offset"`
	// The maximum number of entries per page.
	Limit string `json:"limit"`
	// The total number of entries seen.
	Count string `json:"count"`
}
